# $Id: makefile.bsd,v 1.2 2002/07/13 16:56:52 stas Rel $
#
# FreeBSD / NetBSD makefile for building fidoconfig documentation
# (legacy makefile, no dynlibs, no huskymak support)
#
# Use with GNU version of make (gmake, see ports collection)

include makefile.unx
