# PntStr make file
#
# $Id: Makefile,v 1.1 2002/06/17 05:37:06 stas Exp $
#

include ../huskymak.cfg

install:
	$(INSTALL) $(IBOPT) pntstr.pl $(BINDIR)

uninstall:
	-$(RM) $(RMOPT) $(BINDIR)$(DIRSEP)pntstr.pl
